DROP DATABASE IF EXISTS oms_iad;
CREATE DATABASE amon WITH OWNER=root ENCODING='UTF8';
CREATE DATABASE oms_iad WITH OWNER=root ENCODING='UTF8';
CREATE DATABASE quartz WITH OWNER=root ENCODING='UTF8';
